version: "3"
services:
  firebase:
    env_file:
      - .env
    build: .
    volumes:
      - .:/firebase
    tty: true
    working_dir: /firebase
    command: bash
    ports:
      - 4000:4000 # Emulator Suite UI
      #- 5000:5000 # Firebase Hosting
      #- 5001:5001 # Clound Functions
      - 9000:9000 # Realtime Database
      #- 8080:8080 # Cloud Firestore
      #- 8085:8085 # Cloud Pub/Sub